export const INDUSTRY: string[] = [
  "<br>",
  "<span class='command'>COMPETITIONS</span>",
  "<br>",
  "• National Collegiate Cyber Defense Competition (NCCDC)",
  "  - 1x Indiana Qualifier",
  "  - 1x Midwest Qualifier", 
  "  - 1x National Appearance",
  "<br>",
  "• Collegiate Penetration Testing Competition (CPTC)",
  "  - 2x Appearances",
  "<br>",
  "• University At Buffalo Lockdown (UBUFF)",
  "  - 1x Appearance",
  "<br>",
];
