export const PROJECTS: string[] = [
  "<span class='command'>PROJECT HIGHLIGHTS</span>",
  "<br>",
  "1. Data Center Reorganization",
  "   • Restructured physical & logical layout with Proxmox and ZFS/LVM-thin pools to enhance efficiency, airflow and reliability.",
  "   • Integrated NetBox IPAM, Splunk monitoring, and LDAP to centralize visibility.",
  "<br>",
  "2. Core Infrastructure Dockerization",
  "   • Containerized core services with Docker & Nginx reverse proxy (SSL/TLS, DNS) for secure, scalable access.",
  "   • Implemented version-controlled configs and automated deployments to streamline updates and maintenance.",
  "<br>",
  "3. Local AI Deployment",
  "   • Deployed AI/ML models on internal Linux infrastructure for secure research, reducing reliance on cloud services.",
  "   • Implemented GPU passthrough and containerized environments for reproducible training and inference.",
  "<br>",
  "4. COAL | Cyber Defense Competition Script",
  "   • Built SSH automation tool to mass-execute scripts across hosts; deployed in National CCDC and UBUFF Lockdown.",
  "   • Improved team response time by automating repetitive tasks and standardizing configurations during competitions.",
  "<br>",
  "5. magicLAMP | Automated LAMP Stack Deployment",
  "   • Authored Bash script to provision Linux, Apache, MySQL, PHP stacks, cutting setup time from hours to minutes.",
  "   • Enhanced portability by designing idempotent installs with consistent, tested configurations.",
  "<br>",
  "6. Active Directory Migration",
  "   • Consolidated domains and migrated AD services with hardened DC's and zero downtime.",
  "   • Cut over DNS/DHCP and standardized GPO posture for more secure, centralized policy management.",
  "<br>",
  "7. Proxmox Node Deployment",
  "   • Cluster: PVE 9, tuned corosync, HA priorities, verified quorum.",
  "   • Net & storage: LACP + VLAN trunks; ZFS (RAIDZ2/mirror) and Ceph/NFS/iSCSI w/ multipath.",
  "   • Compute & I/O: CPU pinning/NUMA, reservations, SR-IOV/passthrough, HugePages.",
  "   • Ops: Cloud-init templates, PBS backups + off-site, Prometheus/Grafana, RBAC/2FA.",
  "   • Outcome: More capacity & HA; clean prod/lab separation; faster failover.",
  "<br>",
  "8. SSP Portal Development",
  "   • Catalog: Self-service requests with validation, approvals, audit.",
  "   • Security: Encrypted LDAP (LDAPS).",
  "   • Ingress & security: Nginx, multi-stage images, CSRF/CSP, secrets hygiene.",
  "   • Outcome: Lower ticket volume/MTTR; standardized, auditable changes.",
  "<br>",
  "9. Cyber Club & Incident Response Environment",
  "   • Lab: Proxmox pools, quotas, snapshot/rollback.",
  "   • Network: Segmented VLANs (red/blue/DMZ/mgmt), pfSense edge, per-team subnets.",
  "   • Identity: AD/LDAP with RBAC.",
  "   • Exercises: ATT&CK-mapped (Atomic/Caldera), CTFd scoring, service health checks.",
  "   • Outcome: Repeatable training with measurable detection/response.",
  "<br>",
];
