export const WORK: string[] = [
  "<br>",
  "<span class='command'>WORK EXPERIENCE</span>",
  "<br>",
  "1. Program Developer & Digital Literacy Educator | Ball Venture Grant",
  "   October 2025 - Present | Fort Wayne, IN",
  "<br>",
  "   • Developed and delivered hybrid training sessions for seniors on technology basics and cybersecurity awareness.",
  "   • Built an AI-powered platform to personalize learning, track progress, and provide ongoing digital support.",
  "   • Increased participants in digital confidence and engagement by teaching safe online practices and social connectivity tools.",
  "<br>",
  "2. IT Service Agent | Indiana Institute of Technology",
  "   September 2025 - Present | Fort Wayne, IN",
  "<br>",
  "   • Resolve 100+ IT tickets monthly, troubleshooting network, software, MFA, SSO, Microsoft Office, and hardware issues.",
  "   • Assist in deploying and maintaining campus-wide IT infrastructure for 1,500+ students and faculty.",
  "   • Reduce system downtime by 30% through monitoring and rapid response.",
  "<br>",
  "3. Undergrad Research Assistant | University of Notre Dame",
  "   February 2025 - Present | Remote",
  "<br>",
  "   • Conducted research on blockchain, cryptography, and decentralized storage to support innovative solutions for Web3DB.",
  "   • Implemented backend APIs using Python, FastAPI, and Solidity smart contracts with IPFS-based decentralized data storage.",
  "   • Developed and tested smart contracts ensuring robust and secure on-chain interactions with backend systems.",
  "   • Engineered encryption and access-control modules to enhance distributed security and data integrity.",
  "   • First-author publication in Springer CCIS — 'Secure and Scalable Data Management Using Web3DB.'",
  "<br>",
  "4. Team Lieutenant | Indiana Tech Cyber Warriors",
  "   July 2024 - Present | Fort Wayne, IN",
  "   Unix Specialty Lead | Offensive Security Co-Lead",
  "<br>",
  "   • Leads weekly practice sessions for Unix Specialty while co-leading offensive security and team-wide weekly practice.",
  "   • Provides oversight and guidance in the training efforts of a dynamic team comprising around 20 members.",
  "   • Creates and presents technical writing based on cybersecurity engagements done in competition.",
  "   • Crafts captivating learning exercises to foster continuous skill enhancement and personal growth.",
  "   • Takes the initiative in competition, successfully guides the team to high placements in competitions.",
  "   • Maintains crucial documentation for new member onboarding and knowledge retention.",
  "<br>",
];
