name: Node.js CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22.x] # test LTS + current

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: npm

      - name: Install dependencies
        run: npm ci

      # Optional: TypeScript type-check (no emit)
      - name: Type check
        run: npm run typecheck --if-present

      - name: Build
        run: npm run dev --if-present

      - name: Test
        run: npm test --if-present
